defaults:
  - _self_
  - datapaths: medicare_partd_pde

table: partd_pde
year: 2016

paths:
  basepath: "/path/to/raw"
  crosswalks_path: "/path/to/crosswalks"
  output_path: "output"

tables:
  partd_pde: "conf/datasets/medicare_partd/partd_pde.yaml"

hydra:
  run:
    dir: ${hydra:runtime.cwd}



